channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-tximport =1.30.0
  - r-readr =2.1.5
  - r-jsonlite =1.8.8
  - bioconductor-deseq2 =1.42.0
  - r-rmarkdown =2.28
  - r-tidyverse =2.0.0
  - r-stringr =1.5.1
  - r-pheatmap =1.0.12
  - r-RColorBrewer =1.1.3
  - r-gridExtra =2.3
  - r-purrr =1.0.2
  - r-VennDiagram =1.7.3
  - bioconductor-limma =3.58.1
  - bioconductor-org.hs.eg.db =3.18.0
  - r-dt =0.33
  - bioconductor-enhancedvolcano =1.20.0
  - bioconductor-reactomepa =1.46.0
  - r-devtools =2.4.5
  - r-base =4.1.1